version: "3.7"

services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./iw-acad-hamro-note-be:/iw-acad-hamro-note-be
    ports:
      - 8000:8000
    env_file:
      - ./.env
